/**
 * team-styles.js
 * Mapa de bandera + color principal por selección, usado para pintar
 * JugadaAnimada (y a futuro cualquier plantilla que necesite identidad visual).
 * Si un equipo no está en la lista, se usa un fallback genérico — nunca rompe.
 */

const EQUIPOS = {
  'Argentina':            { flag: '🇦🇷', color: '#75AADB' },
  'Brazil':               { flag: '🇧🇷', color: '#009C3B' },
  'Brasil':               { flag: '🇧🇷', color: '#009C3B' },
  'France':               { flag: '🇫🇷', color: '#0055A4' },
  'Francia':              { flag: '🇫🇷', color: '#0055A4' },
  'Germany':              { flag: '🇩🇪', color: '#1D1D1D' },
  'Alemania':             { flag: '🇩🇪', color: '#1D1D1D' },
  'Spain':                { flag: '🇪🇸', color: '#C60B1E' },
  'España':               { flag: '🇪🇸', color: '#C60B1E' },
  'England':              { flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', color: '#CE1124' },
  'Inglaterra':           { flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', color: '#CE1124' },
  'Portugal':             { flag: '🇵🇹', color: '#FF0000' },
  'Netherlands':          { flag: '🇳🇱', color: '#FF6600' },
  'Países Bajos':         { flag: '🇳🇱', color: '#FF6600' },
  'Holanda':              { flag: '🇳🇱', color: '#FF6600' },
  'Belgium':              { flag: '🇧🇪', color: '#ED2939' },
  'Bélgica':              { flag: '🇧🇪', color: '#ED2939' },
  'Italy':                { flag: '🇮🇹', color: '#0066CC' },
  'Italia':               { flag: '🇮🇹', color: '#0066CC' },
  'Uruguay':              { flag: '🇺🇾', color: '#5CACE2' },
  'Colombia':             { flag: '🇨🇴', color: '#FCD116' },
  'Chile':                { flag: '🇨🇱', color: '#D52B1E' },
  'Mexico':               { flag: '🇲🇽', color: '#006847' },
  'México':               { flag: '🇲🇽', color: '#006847' },
  'United States':        { flag: '🇺🇸', color: '#3C3B6E' },
  'Estados Unidos':       { flag: '🇺🇸', color: '#3C3B6E' },
  'Canada':               { flag: '🇨🇦', color: '#FF0000' },
  'Canadá':               { flag: '🇨🇦', color: '#FF0000' },
  'Croatia':              { flag: '🇭🇷', color: '#FF0000' },
  'Croacia':              { flag: '🇭🇷', color: '#FF0000' },
  'Japan':                { flag: '🇯🇵', color: '#0033A0' },
  'Japón':                { flag: '🇯🇵', color: '#0033A0' },
  'South Korea':          { flag: '🇰🇷', color: '#CD2E3A' },
  'Korea Republic':       { flag: '🇰🇷', color: '#CD2E3A' },
  'Corea del Sur':        { flag: '🇰🇷', color: '#CD2E3A' },
  'Morocco':              { flag: '🇲🇦', color: '#C1272D' },
  'Marruecos':            { flag: '🇲🇦', color: '#C1272D' },
  'Senegal':              { flag: '🇸🇳', color: '#00853F' },
  'Ghana':                { flag: '🇬🇭', color: '#CE1126' },
  'Nigeria':              { flag: '🇳🇬', color: '#008751' },
  'Ecuador':              { flag: '🇪🇨', color: '#FFD100' },
  'Peru':                 { flag: '🇵🇪', color: '#D91023' },
  'Perú':                 { flag: '🇵🇪', color: '#D91023' },
  'Paraguay':             { flag: '🇵🇾', color: '#D52B1E' },
  'Switzerland':          { flag: '🇨🇭', color: '#FF0000' },
  'Suiza':                { flag: '🇨🇭', color: '#FF0000' },
  'Poland':               { flag: '🇵🇱', color: '#DC143C' },
  'Polonia':              { flag: '🇵🇱', color: '#DC143C' },
  'Serbia':               { flag: '🇷🇸', color: '#C6363C' },
  'Denmark':              { flag: '🇩🇰', color: '#C60C30' },
  'Dinamarca':            { flag: '🇩🇰', color: '#C60C30' },
  'Sweden':               { flag: '🇸🇪', color: '#006AA7' },
  'Suecia':               { flag: '🇸🇪', color: '#006AA7' },
  'Australia':            { flag: '🇦🇺', color: '#00843D' },
  'Saudi Arabia':         { flag: '🇸🇦', color: '#006C35' },
  'Arabia Saudita':       { flag: '🇸🇦', color: '#006C35' },
  'Qatar':                { flag: '🇶🇦', color: '#8A1538' },
  'Iran':                 { flag: '🇮🇷', color: '#239F40' },
  'Irán':                 { flag: '🇮🇷', color: '#239F40' },
  'Tunisia':              { flag: '🇹🇳', color: '#E70013' },
  'Túnez':                { flag: '🇹🇳', color: '#E70013' },
  'Costa Rica':           { flag: '🇨🇷', color: '#002B7F' },
  'Panama':               { flag: '🇵🇦', color: '#DA121A' },
  'Panamá':               { flag: '🇵🇦', color: '#DA121A' },
  'Jamaica':              { flag: '🇯🇲', color: '#FED100' },
  'Bolivia':              { flag: '🇧🇴', color: '#D52B1E' },
  'Venezuela':            { flag: '🇻🇪', color: '#FFD100' },
  'New Zealand':          { flag: '🇳🇿', color: '#000000' },
  'Nueva Zelanda':        { flag: '🇳🇿', color: '#000000' },
  'Austria':              { flag: '🇦🇹', color: '#ED2939' },
  'Norway':               { flag: '🇳🇴', color: '#BA0C2F' },
  'Noruega':              { flag: '🇳🇴', color: '#BA0C2F' },
  'Scotland':             { flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', color: '#0065BD' },
  'Escocia':              { flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', color: '#0065BD' },
  'Egypt':                { flag: '🇪🇬', color: '#CE1126' },
  'Egipto':               { flag: '🇪🇬', color: '#CE1126' },
  'Algeria':              { flag: '🇩🇿', color: '#006233' },
  'Argelia':              { flag: '🇩🇿', color: '#006233' },
  'Ivory Coast':          { flag: '🇨🇮', color: '#FF8200' },
  'Costa de Marfil':      { flag: '🇨🇮', color: '#FF8200' },
  'Cameroon':             { flag: '🇨🇲', color: '#007A5E' },
  'Camerún':              { flag: '🇨🇲', color: '#007A5E' },
  'South Africa':         { flag: '🇿🇦', color: '#007A4D' },
  'Sudáfrica':            { flag: '🇿🇦', color: '#007A4D' },
};

const FALLBACK = { flag: '⚽', color: '#C9A84C' };

function estiloEquipo(nombre) {
  return EQUIPOS[nombre] || FALLBACK;
}

module.exports = { estiloEquipo };
